// Package Stalker provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package models

// MetricsList defines model for metricsList.
type MetricsList struct {
	Metrics *[]string `json:"metrics,omitempty"`
}

// GetMetricsListParams defines parameters for GetMetricsList.
type GetMetricsListParams struct {
	// Get metrics from a past time period
	StartTime *int `json:"startTime,omitempty"`

	// Get metrics from a past time period
	EndTime *int `json:"endTime,omitempty"`
}
